# Numpy Turorial

## NumPy array (ndarray)
- A grid of values indexed by non-negative integer
- all values have the same data types(homogeneous)
- It can have any number of dimensions (from 0D to nD)

 In NumPy dimensions are called axes.
 

In [ ]:
[[1., 4., 0.],
 [0., 1., 3.]]

 In the example above example, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

 Note:numpy.array is not same as array.array (Standard Python Library-array: only handles one-dimensional arrays and offers less functionality)

 ## Important attributes of an ndarray object
 - ndarray.ndim: the number of axes (dimensions) of the array
 - ndarray.shape: Size of each dimension (tuple)\
   For a matrix with n rows and m columns, shape will be (n,m)
 - ndarray.size: the total number of elements of the array.\
    This is equal to the product of the elements of shape.
 - ndarray.dtype: Data type of elements
 - ndarray.itemsize: Memory (bytes) per element\
   For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
 - ndarray.data:the buffer containing the actual elements of the array.


In [18]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
a.shape # (3, 5)
a.ndim # 2
a.dtype #dtype('int64')
a.dtype.name #'int64'
a.itemsize #8

8

In [34]:
b = np.array([6, 7, 8])
type(b) #numpy.ndarray

numpy.ndarray

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

# array creation
can create arrays from Python lists or tuples:

In [35]:
import numpy as np

arr1 = np.array([2, 3, 4])
arr2 = np.array([(1, 2, 3), (4, 5, 6)])
print(arr1, arr2)

[2 3 4] [[1 2 3]
 [4 5 6]]


The type of the array can also be explicitly specified at creation time:

In [39]:
c = np.array([[1, 2], [3, 4]], dtype=np.float64)
print(c)
print(c.dtype)

[[1. 2.]
 [3. 4.]]
float64


### np.zeros(shape)
Creates an array of zeros

In [42]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.ones(shape)
Creates an array of ones

In [54]:
arr=np.ones((2, 3), dtype=np.int16)
print(arr)
np.ones((2, 3, 4), dtype=np.int16)

[[1 1 1]
 [1 1 1]]


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

### np.empty(shape)
Creates an uninitialized array\
creates an array whose initial content is random and depends on the state of the memory. 

In [58]:
print(np.empty((2, 3)))
np.empty((2,3,4)) 

[[6.23042070e-307 1.33512376e-306 1.11261230e-306]
 [7.56577399e-307 9.34600963e-307 1.05699581e-307]]


array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         7.56595733e-307],
        [3.44902066e-307, 1.60214553e-306, 6.23054972e-307,
         4.22786781e-307],
        [4.22777954e-307, 1.69119330e-306, 4.45063154e-308,
         7.56571287e-307]],

       [[4.22774898e-307, 1.33511290e-306, 6.67535739e-308,
         8.90104239e-307],
        [1.33511290e-306, 1.69120281e-306, 1.69114441e-306,
         1.33511426e-306],
        [1.78020848e-306, 1.86916797e-306, 6.23061763e-307,
         2.00753299e-317]]])

### np.arange(start, stop, step)
Like Python range, returns array

In [62]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

In [59]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [60]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### np.linspace(start, stop, n)
Returns n evenly spaced values\
receives as an argument the number of elements that we want, instead of the step:

In [68]:
from numpy import pi
np.linspace(0, 2, 9)               # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [66]:
x = np.linspace(0, 2 * pi, 100)       # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [74]:
f = np.sin(x)
print(f)
np.cos(x)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

array([ 1.        ,  0.99798668,  0.99195481,  0.9819287 ,  0.9679487 ,
        0.95007112,  0.92836793,  0.90292654,  0.87384938,  0.84125353,
        0.80527026,  0.76604444,  0.72373404,  0.67850941,  0.63055267,
        0.58005691,  0.52722547,  0.47227107,  0.41541501,  0.35688622,
        0.29692038,  0.23575894,  0.17364818,  0.1108382 ,  0.04758192,
       -0.01586596, -0.07924996, -0.14231484, -0.20480667, -0.26647381,
       -0.32706796, -0.38634513, -0.44406661, -0.5       , -0.55392006,
       -0.60560969, -0.65486073, -0.70147489, -0.74526445, -0.78605309,
       -0.82367658, -0.85798341, -0.88883545, -0.91610846, -0.93969262,
       -0.95949297, -0.97542979, -0.98743889, -0.99547192, -0.99949654,
       -0.99949654, -0.99547192, -0.98743889, -0.97542979, -0.95949297,
       -0.93969262, -0.91610846, -0.88883545, -0.85798341, -0.82367658,
       -0.78605309, -0.74526445, -0.70147489, -0.65486073, -0.60560969,
       -0.55392006, -0.5       , -0.44406661, -0.38634513, -0.32

# Basic Operations

In [77]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
print(a - b) 
print(b**2)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]


In [79]:
A = np.array([[1,1],[0,1]])
print(A)
B = np.array([[2,0],[3,4]])
print(A * B)   # element-wise
print(A @ B)   # matrix multiplication
print(A.dot(B))

[[1 1]
 [0 1]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [82]:
a = np.ones((2, 3), dtype=np.int_)
print(a)
a*=5
a

[[1 1 1]
 [1 1 1]]


array([[5, 5, 5],
       [5, 5, 5]])

In [89]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = rg.random((2, 3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
3.290252281866131
0.14415961271963373
0.9504636963259353


#### axis- parameter
by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [91]:
b = np.arange(8).reshape(2, 4)
print(b)
print(b.sum(axis=0))     # sum of each column
print(b.min(axis=1))     # min of each row
print(b.cumsum(axis=1))  # cumulative sum along each row

[[0 1 2 3]
 [4 5 6 7]]
[ 4  6  8 10]
[0 4]
[[ 0  1  3  6]
 [ 4  9 15 22]]


### Universal Functions (ufuncs)

In [98]:
import numpy as np

print(np.sqrt(np.array([0, 1, 4, 9])))
print(np.exp(np.array([1, 2, 3])))
a=np.array([0, 1, 4, 9])
b=(np.array([1, 2, 3,4]))
print(np.sqrt(b))
np.add(a,b)

[0. 1. 2. 3.]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081 2.        ]


array([ 1,  3,  7, 13])

In [103]:
c=np.array([2.3, -1.4, 4.5])
print(np.ceil(c))
print(np.floor(c))
np.mean(c)

[ 3. -1.  5.]
[ 2. -2.  4.]


np.float64(1.8)

### Axis and Shape Manipulation
Axis 0 → rows\
Axis 1 → columns

In [104]:
b = np.arange(12).reshape(3,4)
print(b.sum(axis=0))  # sum columns
print(b.sum(axis=1))  # sum rows

[12 15 18 21]
[ 6 22 38]


In [5]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

## Indexing & Slicing

In [6]:
a = np.arange(10)**3
print(a)
print(a[2])

print(a[2:4])
print(a[::-1])

for i in a:
    print(i**(1 / 3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27]
[729 512 343 216 125  64  27   8   1   0]
0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


## Indexing and Slicing(Multidimensional arrays)
Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:


In [122]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=np.int_)j5jht7i7
print(b)
print(b[2, 3]) 
print(b[:,1])     # second column of all rows
print(b[0:5, 2])  # row in the third column of b
print(b[1:3, :])  # each column in the second and third row of b
b[1:3, :3]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 2 12 22 32 42]
[[10 11 12 13]
 [20 21 22 23]]


array([[10, 11, 12],
       [20, 21, 22]])